version: v1beta1
mappings:
  - fromVirtualCluster:
      # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
      apiVersion: cert-manager.io/v1
      kind: Issuer
      patches:
        - op: rewriteName
          path: spec.ca.secretName
          sync:
            secret: true
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
  - fromVirtualCluster:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      patches:
        - op: rewriteName
          path: spec.issuerRef.name
        - op: rewriteName
          path: spec.secretName
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
        - op: copyFromObject
          fromPath: spec.issuerRef.name
          path: metadata.annotations['test.loft.sh/issuerRefName']
        - op: rewriteName
          path: metadata.annotations['test.loft.sh/issuerRefName']
      syncBack:
        - kind: Secret
          apiVersion: v1
          selectors:
            - name:
                rewrittenPath: spec.secretName
          patches:
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/certificate-name']
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/issuer-name']